services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      SQLITE_PATH: /app/data/nutribot.db
    volumes:
      - nutribot_sqlite:/app/data

volumes:
  nutribot_sqlite:
